#!/bin/bash

set -o errexit
set -o nounset
set -o xtrace

fetch_metrics(){
  readonly DST=$1
  readonly CMD="s3cmd --config ${HOME}/.amazon-aws.cfg"
  readonly SRC="s3://nucleotid-es/metrics/quast/"
  ${CMD} sync ${SRC} ${DST}
}

format_results(){
  mkdir -p data
  ruby \
    -I lib \
    -rdata_processor \
    -e "include DataProcessor" \
    -e "execute! ${DIR}" \
    > data/results.yml
}

bundle install

DIR=tmp/metrics/
mkdir -p ${DIR}
MASTER=tmp/master.csv

fetch_metrics ${DIR}
#format_results ${DIR} ${MASTER}
