#!/bin/bash

set -o errexit
set -o nounset
set -o xtrace

fetch_contigs(){
  local readonly DST=$1
  local readonly CMD="s3cmd --config ${HOME}/.amazon-aws.cfg"
  local readonly DIR="s3://nucleotid-es/evaluations/"

  mkdir -p ${DST}
  ${CMD} sync --rexclude=".+/log.txt" --skip-existing ${DIR} ${DST}
}

fetch_references(){
  local readonly DST=$1
  local readonly CMD="s3cmd --config ${HOME}/.amazon-aws.cfg"
  local readonly DIR="s3://nucleotid-es/reference/"

  mkdir -p ${DST}
  ${CMD} sync --skip-existing ${DIR} ${DST}
}

fetch_master_list(){
  local readonly DST=$1
  local readonly CMD="s3cmd --config ${HOME}/.amazon-aws.cfg"
  local readonly FILE="s3://nucleotid-es/evaluation_master_list.csv"
  ${CMD} get ${FILE} ${DST}
}

delete_empty_files(){
  local readonly DIR=$1
  find tmp/contigs/*/contigs.fa -empty | xargs rm
}

function quast (){
  set -o errexit
  set -o nounset
  set -o xtrace

  local readonly DIR=$3
  local readonly REFERENCE="${DIR}/references/${1}.fa"
  local readonly CONTIGS="${DIR}/contigs/${2}/contigs.fa"
  local readonly TMP=$(gmktemp -d)
  local readonly DST="${DIR}/quast/${2}"

  /usr/local/bin/quast.py \
    -R ${REFERENCE} \
    --min-contig 1000 \
    --output-dir ${TMP} \
    --no-plots \
    --threads 1 \
    ${CONTIGS}

  mkdir -p ${DST}
  cp ${TMP}/report.tsv ${DST}
}
export -f quast

push_metrics(){
  local readonly SRC=$1
  local readonly CMD="s3cmd --config ${HOME}/.amazon-aws.cfg"
  local readonly DST="s3://nucleotid-es/metrics/"
  ${CMD} sync ${SRC} ${DST}
}


LOC=tmp
MASTER=${LOC}/master.csv
fetch_contigs ${DIR}/contigs
delete_empty_files ${LOC}/contigs
fetch_references ${LOC}/references
fetch_master_list ${MASTER}

export SHELL=/bin/bash
parallel \
    --env SHELL \
    --env quast \
    --max-procs 8 \
    --col-sep ',' \
    --header 1 \
    "quast {dataset} {digest} tmp"\
    :::: ${MASTER}

push_metrics ${LOC}/quast
