#!/bin/bash

set -o errexit
set -o nounset

is_ready(){
    echo -n "Publish changes to S3 (yes|no) ? "
    read INPUT

    if [[ "${INPUT}" != 'yes' ]]; then
        echo "Aborting."
        exit 1
    fi
}

push(){
  git push
}

build(){
    echo "Building site ..."
    ./script/build > /dev/null
    readonly status=$?
    if [ $status -ne 0 ]; then
        echo "Error building site." >&2
        exit 1
    fi
}

publish(){
    echo "Pushing site ..."

    readonly local cmd="s3cmd --config ${HOME}/.nucleotides.s3cfg"
    readonly local bucket="s3://nucleotid.es/"
    readonly local src="build/*"

    ${cmd} sync --delete-removed ${src} ${bucket} 2> /dev/null
    if [ $status -ne 0 ]; then
        echo "Error pushing site." >&2
        exit 1
    fi
    echo "Complete."

}

is_ready
push
build
publish
