#!/bin/bash

set -o errexit
set -o nounset

echo "Publish changes to heroku (yes|no) ?"
read INPUT

if [[ "${INPUT}" != 'yes' ]]; then
    echo "Aborting."
    exit 1
fi

echo "Pushing changes ..."
BRANCH="heroku-$(date +%s)"
trap "git branch -D ${BRANCH}" SIGHUP SIGINT SIGTERM

git push
git checkout -b ${BRANCH} master
./script/build
git add -f build
git commit -m "Rebuild updated site"
git push -f heroku ${BRANCH}:refs/heads/master
git checkout master
