#!/usr/bin/env ruby

require 'csv'
require 'yaml'

scores = ARGV.
  map{|f| CSV.read(f)}.
  flatten(1).
  map{|var, image, score| [var, image.split('/'), score].flatten }.
  map{|i| [:var, :maintainer, :image, :task, :score].zip(i) }.
  map{|i| Hash[i]}

output = {}
output[:names] = scores.map{|i| i[:var].to_sym}.uniq
output[:variables] = scores.inject(Hash.new) do |hash, score|
  hash[score[:maintainer]] ||= {}
  hash[score[:maintainer]][score[:image]] ||= {}
  hash[score[:maintainer]][score[:image]][score[:task]] ||= {}
  hash[score[:maintainer]][score[:image]][score[:task]] ||= {}
  hash[score[:maintainer]][score[:image]][score[:task]][score[:var].to_sym] = score[:score]
  hash
end

puts YAML.dump(output)
