#!/usr/bin/env ruby

credential_file, key = ARGV

value = File.read(credential_file).
  lines.
  map{|i| i.split('=')}.
  detect{|(k,_)| k == key }

if value.nil?
  STDERR.puts "No value found for: #{key}"
  exit 1
else
  STDOUT.print value.last.strip
  exit 0
end
